server:
  port: 8081
  servlet:
    context-path: /optics

spring:
  datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
  s3:
    bucket-name: optics-management-storage
    region: ap-southeast-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  signerKey: ${JWT_SIGNER_KEY:dev-jwt-signer-key}
  valid-duration: ${VALID_DURATION:3600}
  refreshable-duration: ${REFRESH_DURATION:86400}

app:
  frontend-url: ${FRONTEND_URL}

ghn:
  base-url: https://dev-online-gateway.ghn.vn/shiip/public-api/v2/
  token: 641ea953-123c-11f1-a3d6-dac90fb956b5
  shop-id: "199410"

openai:
  api-key: ${OPENAI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always